const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const labels={smart_short:"SMART short self-test",smart_long:"SMART extended self-test",speed:"Read speed + random IOPS",surface_read:"Full non-destructive surface read",destructive_verify:"Destructive write/read verification"};
const seed=()=>({
  drives:[
    {id:"exos",path:"/dev/sda",model:"Seagate Exos X18",serial:"ZRS1A2BC",capacity:"18.0 TB",transport:"SATA",status:"ready",smart:"Passed",temp:"34 °C",hours:"18,421 h",farm:"Available",pending:0,reallocated:0,uncorrectable:0,crc:0,integrity:"consistent",integrityLabel:"History consistent",integrityEvidence:["SMART power-on hours align with FARM workload totals.","No counter rollback or implausible zeroed lifetime fields detected."],attributes:[[1,"Raw Read Error Rate",100,100,44,"0"],[5,"Reallocated Sector Count",100,100,10,"0"],[7,"Seek Error Rate",87,60,45,"388,201,994"],[9,"Power-On Hours",79,79,0,"18,421"],[187,"Reported Uncorrectable",100,100,0,"0"],[197,"Current Pending Sector",100,100,0,"0"],[198,"Offline Uncorrectable",100,100,0,"0"]],farmData:[["Head load events","42,118"],["Lifetime writes","171.4 TB"],["Lifetime reads","2.81 PB"],["Max head temperature","48 °C"],["Unrecoverable read errors","0"],["High priority unloads","3"]]},
    {id:"nvme",path:"/dev/nvme0n1",model:"Samsung SSD 990 PRO",serial:"S7H9NJ0W401234",capacity:"2.0 TB",transport:"NVMe",status:"ready",smart:"Passed",temp:"41 °C",hours:"2,108 h",farm:"Not applicable",pending:0,reallocated:0,uncorrectable:0,crc:0,integrity:"consistent",integrityLabel:"History consistent",integrityEvidence:["NVMe power-on hours, percentage used, and data-unit counters are mutually plausible."],attributes:[[1,"Critical Warning",0,0,0,"0"],[2,"Composite Temperature",0,0,0,"314 K"],[3,"Available Spare",100,100,10,"100%"],[5,"Percentage Used",3,3,0,"3%"],[9,"Power-On Hours",0,0,0,"2,108"],[13,"Media and Data Errors",0,0,0,"0"]],farmData:[]},
    {id:"usb",path:"/dev/sdb",model:"WD Elements 25A3",serial:"WX52D91K7R30",capacity:"8.0 TB",transport:"USB",status:"limited",smart:"Bridge blocked",temp:"—",hours:"—",farm:"Unavailable",pending:"—",reallocated:"—",uncorrectable:"—",crc:"—",integrity:"indeterminate",integrityLabel:"Cannot assess history",integrityEvidence:["The USB bridge blocks the lifetime counters required for consistency analysis."],attributes:[],farmData:[],reason:"The USB bridge does not pass SMART commands. Read-only host tests remain available."},
    {id:"wedged",path:"/dev/sdc",model:"Seagate BarraCuda Compute",serial:"ZFL6D3EF",capacity:"4.0 TB",transport:"SATA",status:"quarantined",smart:"Last known: Warning",temp:"—",hours:"12,993 h",farm:"Unavailable",pending:8,reallocated:24,uncorrectable:2,crc:7,integrity:"indeterminate",integrityLabel:"Stale snapshot only",integrityEvidence:["The drive is quarantined; current counters cannot be safely compared."],attributes:[[5,"Reallocated Sector Count",91,91,10,"24"],[187,"Reported Uncorrectable",98,98,0,"2"],[197,"Current Pending Sector",92,92,0,"8"],[199,"UDMA CRC Error Count",200,200,0,"7"]],farmData:[],reason:"The hardware command ignored termination and may be blocked in the kernel. Automatic probes are disabled."},
    {id:"suspect",path:"/dev/sdd",model:"Seagate IronWolf Pro",serial:"WUH91RESET",capacity:"12.0 TB",transport:"SATA",status:"ready",smart:"Passed",temp:"32 °C",hours:"43 h",farm:"Available",pending:0,reallocated:0,uncorrectable:0,crc:0,integrity:"suspicious",integrityLabel:"Possible SMART history reset",integrityEvidence:["SMART reports only 43 power-on hours while FARM records 27,904 spindle hours.","SMART lifetime reads are near zero while FARM reports 2.37 PB.","Power-cycle and head-load history are implausible for the reported SMART age."],attributes:[[1,"Raw Read Error Rate",100,100,44,"0"],[5,"Reallocated Sector Count",100,100,10,"0"],[9,"Power-On Hours",100,100,0,"43"],[12,"Power Cycle Count",100,100,0,"3"],[197,"Current Pending Sector",100,100,0,"0"],[241,"Total LBAs Written",100,100,0,"1,201"],[242,"Total LBAs Read",100,100,0,"8,490"]],farmData:[["FARM spindle hours","27,904 h"],["Head load events","193,882"],["Lifetime writes","681.2 TB"],["Lifetime reads","2.37 PB"],["Power cycles","1,438"],["Factory reset events","1"]],reason:"SMART health passes, but independent lifetime counters are inconsistent. Review the history analysis before accepting this drive."}
  ],
  tests:[
    {id:"JOB-1048",suite:"SUITE-318",step:3,totalSteps:4,drive:"/dev/sda",driveId:"exos",kind:"Full surface read",kindId:"surface_read",status:"running",progress:64.7,phase:"Reading 11.65 TB of 18.0 TB",speed:"243 MB/s",created:"Today, 10:14",errors:0,badBlocks:[],slowBlocks:[173]},
    {id:"JOB-1047",suite:"SUITE-317",step:2,totalSteps:2,drive:"/dev/nvme0n1",driveId:"nvme",kind:"Read speed + random IOPS",kindId:"speed",status:"completed",progress:100,phase:"Complete",speed:"6.81 GB/s · 1.21M IOPS",created:"Today, 09:42",errors:0},
    {id:"JOB-1046",suite:"SUITE-318",step:2,totalSteps:4,drive:"/dev/sda",driveId:"exos",kind:"SMART extended self-test",kindId:"smart_long",status:"warning",progress:100,phase:"Completed with policy warning",speed:"—",created:"Yesterday, 22:08",errors:0},
    {id:"JOB-1045",suite:"SUITE-316",step:1,totalSteps:1,drive:"/dev/sdb",driveId:"usb",kind:"Full surface read",kindId:"surface_read",status:"paused",progress:28.3,phase:"Paused at 2.26 TB checkpoint",speed:"171 MB/s",created:"Yesterday, 18:31",errors:2,badBlocks:[41,68],slowBlocks:[67,69,92]},
    {id:"JOB-1044",suite:"SUITE-315",step:1,totalSteps:1,drive:"/dev/sdd",driveId:"suspect",kind:"SMART history consistency analysis",kindId:"smart_short",status:"warning",progress:100,phase:"Independent SMART and FARM counters conflict",speed:"—",created:"Yesterday, 16:04",errors:0}
  ],
  reports:[
    {id:"RPT-7F19A2",job:"JOB-1047",drive:"Samsung SSD 990 PRO",verdict:"PASS",created:"Today, 10:02",hash:"89f0d12a7e9be20361d0496e69b5f1c9a3f4c25aa0a0630bd8713ff91b72e07a"},
    {id:"RPT-B42C11",job:"JOB-1046",drive:"Seagate Exos X18",verdict:"WARNING",created:"Yesterday, 23:47",hash:"3e0a509d2d584725c8f5d70585e991ab12f39d24505e41638adbd97b622e241d"},
    {id:"RPT-RESET9",job:"JOB-1044",drive:"Seagate IronWolf Pro",verdict:"WARNING",created:"Yesterday, 16:12",hash:"f41b628cc2312cb312e7acff397d9ace3e410f52c895f030af5fa09192b61206"}
  ],
  users:[{name:"admin",role:"Administrator"},{name:"burnin-operator",role:"Operator"},{name:"qa-viewer",role:"Viewer"}],
  audit:[{time:"11:03:14",action:"device.quarantine",actor:"system",target:"/dev/sdc"},{time:"10:14:03",action:"suite.start",actor:"burnin-operator",target:"SUITE-318"},{time:"10:02:48",action:"report.generate",actor:"admin",target:"RPT-7F19A2"},{time:"09:42:11",action:"job.complete",actor:"system",target:"JOB-1047"}]
});
let data=seed(), selectedReport=null, selectedSmart=null, selectedMapJob="JOB-1048", selectedDetailDrive=null, selectedDetailTest=null, toastTimer, nextJob=1050, nextSuite=319;
const esc=(v="")=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const statusText=s=>s[0].toUpperCase()+s.slice(1).replaceAll("_"," ");
function toast(message){const el=$("#toast");el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3200)}
function render(){
  $("#summary").innerHTML=[["Physical drives",data.drives.length],["Ready",data.drives.filter(d=>d.status==="ready").length],["Quarantined",data.drives.filter(d=>d.status==="quarantined").length],["Active suites",new Set(data.tests.filter(t=>["running","queued","paused"].includes(t.status)).map(t=>t.suite)).size]].map(([l,v])=>`<div class="metric"><span>${l}</span><strong>${v}</strong></div>`).join("");
  $("#drive-grid").innerHTML=data.drives.map(d=>`<article class="drive-card ${d.status}"><div class="drive-head"><div><h3>${esc(d.model)}</h3><button class="path-link" data-drive-detail="${d.id}" title="Open full-screen drive workspace">${esc(d.path)} · ${esc(d.transport)} <span>OPEN ↗</span></button></div><span class="status status-${d.status}">${statusText(d.status)}</span></div><div class="facts"><div class="fact"><span>Serial</span><strong>${esc(d.serial)}</strong></div><div class="fact"><span>Capacity</span><strong>${d.capacity}</strong></div><div class="fact"><span>SMART</span><strong>${d.smart}</strong></div><div class="fact"><span>Temperature</span><strong>${d.temp}</strong></div><div class="fact"><span>Power-on time</span><strong>${d.hours}</strong></div><div class="fact"><span>Seagate FARM</span><strong>${d.farm}</strong></div><div class="fact"><span>SMART history</span><strong>${d.integrityLabel}</strong></div></div>${d.reason?`<div class="reason">${esc(d.reason)}</div>`:""}<div class="actions">${d.status==="quarantined"?`<button class="tonal" data-retry="${d.id}">Retry manually</button>`:`<button class="filled" data-test="${d.id}">Build test suite</button>`}<button class="text-button" data-smart="${d.id}">View SMART / FARM</button></div></article>`).join("");
  const table=testsTable(data.tests);$("#test-table").innerHTML=table;$("#recent-tests").innerHTML=testsTable(data.tests.slice(0,5));
  $("#report-grid").innerHTML=data.reports.map(r=>`<article class="report-card"><span class="status status-${r.verdict==="PASS"?"completed":"warning"}">${r.verdict}</span><h3>${r.drive}</h3><p>${r.id} · ${r.job}</p><p class="hash">SHA-256 ${r.hash}</p><div class="actions"><button class="filled" data-report="${r.id}">Preview</button><button class="tonal" data-verify="${r.id}">Verify hash</button></div></article>`).join("");
  $("#user-list").innerHTML=data.users.map(u=>`<div class="user-row"><strong>${esc(u.name)}</strong><span>${u.role}</span></div>`).join("");
  $("#audit-table").innerHTML=`<table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Target</th></tr></thead><tbody>${data.audit.map(a=>`<tr><td>${a.time}</td><td>${a.action}</td><td>${a.actor}</td><td>${a.target}</td></tr>`).join("")}</tbody></table>`;
  renderMapSelector();renderDriveMap();if(selectedDetailDrive&&$("#drive-workspace").open)renderDriveWorkspace();
}
function testsTable(items){return`<table><thead><tr><th>Drive / suite</th><th>Status</th><th>Progress</th><th>Phase</th><th>Performance</th><th>Actions</th></tr></thead><tbody>${items.map(t=>{let actions=t.status==="running"?`${t.kindId==="surface_read"?`<button data-job="map" data-id="${t.id}">Drive map</button>`:""}<button data-job="pause" data-id="${t.id}">Pause</button><button data-job="cancel" data-id="${t.id}">Cancel suite</button>`:t.status==="paused"?`<button data-job="map" data-id="${t.id}">Drive map</button><button data-job="resume" data-id="${t.id}">Resume</button><button data-job="cancel" data-id="${t.id}">Cancel suite</button>`:t.status==="queued"?`<button data-job="cancel" data-id="${t.id}">Cancel suite</button>`:`<button data-job="report" data-id="${t.id}">PDF report</button>`;return`<tr><td><button class="path-link" data-drive-detail="${t.driveId}">${t.drive} <span>OPEN ↗</span></button><br><small>${t.kind} · ${t.id}</small><br><small>${t.suite} · step ${t.step} of ${t.totalSteps}</small></td><td><span class="status status-${t.status}">${statusText(t.status)}</span></td><td><div class="progress"><i style="width:${t.progress}%"></i></div><small>${t.progress.toFixed(1)}%</small></td><td>${t.phase}${t.errors?`<br><small>${t.errors} unreadable blocks</small>`:""}</td><td>${t.speed}</td><td><div class="actions">${actions}</div></td></tr>`}).join("")}</tbody></table>`}
function renderMapSelector(){
  const scans=data.tests.filter(t=>t.kindId==="surface_read"),select=$("#map-test-select");
  if(!scans.some(t=>t.id===selectedMapJob)&&scans[0])selectedMapJob=scans[0].id;
  select.innerHTML=scans.map(t=>`<option value="${t.id}" ${t.id===selectedMapJob?"selected":""}>${t.drive} · ${t.id} · ${statusText(t.status)}</option>`).join("");
}
function renderDriveMap(){
  const test=data.tests.find(t=>t.id===selectedMapJob),map=$("#drive-map"),meta=$("#map-meta");if(!test){map.innerHTML="";meta.textContent="No surface scan selected";return}
  const cells=384,scanned=Math.floor(cells*test.progress/100),current=Math.min(cells-1,scanned),bad=new Set(test.badBlocks||[]),slow=new Set(test.slowBlocks||[]);
  map.innerHTML=Array.from({length:cells},(_,i)=>{let type=i>scanned?"pending":i===current?"current":bad.has(i)?"bad":slow.has(i)?"slow":"good";return`<i class="map-${type}" title="LBA range ${i+1} of ${cells} · ${type==="bad"?"unreadable":type==="slow"?"slow / retrying":type}"></i>`}).join("");
  const d=data.drives.find(x=>x.id===test.driveId);meta.innerHTML=`<span><strong>${test.progress.toFixed(1)}%</strong> scanned</span><span><strong>${test.speed}</strong> current rate</span><span><strong>${bad.size}</strong> unreadable ranges</span><span><strong>${slow.size}</strong> slow / retry ranges</span><span>${d?.model||test.drive}</span>`;
}
function detailJobActions(t){
  if(!t)return"";
  if(t.status==="running")return`<button class="tonal" data-job="pause" data-id="${t.id}">Pause test</button><button class="text-button" data-job="cancel" data-id="${t.id}">Cancel suite</button>`;
  if(t.status==="paused")return`<button class="filled" data-job="resume" data-id="${t.id}">Resume test</button><button class="text-button" data-job="cancel" data-id="${t.id}">Cancel suite</button>`;
  if(t.status==="queued")return`<button class="text-button" data-job="cancel" data-id="${t.id}">Cancel suite</button>`;
  return`<button class="tonal" data-job="report" data-id="${t.id}">Generate PDF report</button>`;
}
function detailMapMarkup(test){
  if(!test)return`<div class="workspace-empty">No surface scan has been run on this drive.</div>`;
  const cells=384,scanned=Math.floor(cells*test.progress/100),current=Math.min(cells-1,scanned),bad=new Set(test.badBlocks||[]),slow=new Set(test.slowBlocks||[]);
  return`<div class="map-meta"><span><strong>${test.progress.toFixed(1)}%</strong> scanned</span><span><strong>${esc(test.speed)}</strong> current rate</span><span><strong>${bad.size}</strong> unreadable ranges</span><span><strong>${slow.size}</strong> slow / retry ranges</span><span>${esc(test.id)}</span></div><div class="drive-map workspace-map" role="img" aria-label="Full surface scan block map">${Array.from({length:cells},(_,i)=>{let type=i>scanned?"pending":i===current?"current":bad.has(i)?"bad":slow.has(i)?"slow":"good";return`<i class="map-${type}" title="LBA range ${i+1} of ${cells} · ${type==="bad"?"unreadable":type==="slow"?"slow / retrying":type}"></i>`}).join("")}</div><div class="map-legend"><span><i class="map-good"></i>Read successfully</span><span><i class="map-current"></i>Current range</span><span><i class="map-slow"></i>Slow / retrying</span><span><i class="map-bad"></i>Unreadable</span><span><i class="map-pending"></i>Not scanned</span></div>`;
}
function openDriveWorkspace(id){
  const d=data.drives.find(x=>x.id===id);if(!d)return;
  selectedDetailDrive=id;const jobs=data.tests.filter(t=>t.driveId===id);selectedDetailTest=jobs.find(t=>["running","paused"].includes(t.status))?.id||jobs[0]?.id||null;
  renderDriveWorkspace();$("#drive-workspace").showModal();
}
function renderDriveWorkspace(){
  const d=data.drives.find(x=>x.id===selectedDetailDrive);if(!d)return;
  const workspace=$("#drive-workspace"),savedScroll=workspace.scrollTop,focusedId=document.activeElement?.id;
  const jobs=data.tests.filter(t=>t.driveId===d.id),active=jobs.find(t=>t.id===selectedDetailTest)||jobs.find(t=>["running","paused","queued"].includes(t.status))||jobs[0]||null;
  selectedDetailTest=active?.id||null;const surface=jobs.find(t=>t.kindId==="surface_read"&&["running","paused"].includes(t.status))||jobs.find(t=>t.kindId==="surface_read");
  $("#workspace-title").textContent=d.model;$("#workspace-path").textContent=`${d.path} · ${d.transport} · ${d.capacity}`;$("#workspace-status").innerHTML=`<span class="status status-${d.status}">${statusText(d.status)}</span>`;
  const smartRows=d.attributes.length?d.attributes.map(a=>`<tr><td>${esc(a[0])}</td><td>${esc(a[1])}</td><td>${esc(a[2])}</td><td>${esc(a[3])}</td><td>${esc(a[4])}</td><td>${esc(a[5])}</td></tr>`).join(""):`<tr><td colspan="6">SMART attributes are unavailable through this transport.</td></tr>`;
  const farmRows=d.farmData.length?d.farmData.map(([metric,value])=>`<tr><td>${esc(metric)}</td><td><strong>${esc(value)}</strong></td><td><span class="source-chip">FARM log</span></td><td>Lifetime counter</td></tr>`).join(""):`<tr><td colspan="4">${d.farm==="Not applicable"?"FARM does not apply to this device.":"FARM data is unavailable through this transport."}</td></tr>`;
  const historyRows=jobs.length?jobs.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.kind)}</td><td><span class="status status-${t.status}">${statusText(t.status)}</span></td><td>${t.progress.toFixed(1)}%</td><td>${esc(t.phase)}</td><td>${esc(t.speed)}</td></tr>`).join(""):`<tr><td colspan="6">No tests have been run on this drive.</td></tr>`;
  const activePanel=active?`<div class="live-progress"><div class="progress-ring" role="progressbar" aria-label="${esc(active.kind)} progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${active.progress.toFixed(1)}" style="--detail-progress:${active.progress}"><strong>${active.progress.toFixed(1)}%</strong><span>complete</span></div><div><span class="status status-${active.status}">${statusText(active.status)}</span><h3>${esc(active.kind)}</h3><p class="supporting">${esc(active.phase)}</p><div class="job-detail-list"><div class="job-detail"><span>Suite step</span><strong>${active.step} of ${active.totalSteps}</strong></div><div class="job-detail"><span>Performance</span><strong>${esc(active.speed)}</strong></div><div class="job-detail"><span>Errors</span><strong>${active.errors||0}</strong></div></div><div class="actions workspace-actions">${detailJobActions(active)}</div></div></div>`:`<div class="workspace-empty">No test is currently associated with this drive.</div>`;
  $("#workspace-content").innerHTML=`<div class="workspace-hero"><section class="workspace-panel"><p class="eyebrow">Drive condition</p><h3>${esc(d.model)}</h3><p class="supporting">Serial ${esc(d.serial)} · telemetry remains readable while isolated test workers are active.</p><div class="workspace-overview">${[["SMART health",d.smart],["Temperature",d.temp],["Power-on hours",d.hours],["Pending sectors",d.pending],["Reallocated",d.reallocated],["Uncorrectable",d.uncorrectable]].map(([label,value])=>`<div class="smart-metric"><span>${label}</span><strong>${esc(value)}</strong></div>`).join("")}</div></section><section class="workspace-panel"><div class="workspace-section-head"><div><p class="eyebrow">Live progress</p><h3>Selected test</h3></div>${jobs.length>1?`<label class="job-selector">View test<select id="workspace-test-select">${jobs.map(t=>`<option value="${t.id}" ${t.id===active?.id?"selected":""}>${t.id} · ${statusText(t.status)} · ${t.kind}</option>`).join("")}</select></label>`:""}</div>${activePanel}</section></div><section class="workspace-panel workspace-section"><div class="workspace-section-head"><div><p class="eyebrow">Real-time media view</p><h3>Full surface map</h3></div><span>Each tile represents an equal LBA range</span></div>${detailMapMarkup(surface)}</section><section class="workspace-section integrity-card workspace-integrity ${d.integrity}"><h3>${esc(d.integrityLabel)}</h3>${d.integrityEvidence.map(item=>`<p>• ${esc(item)}</p>`).join("")}<p><strong>Heuristic only:</strong> counter inconsistencies can indicate a reset but do not prove intentional wiping.</p></section><section class="workspace-section"><div class="workspace-section-head"><div><p class="eyebrow">Complete device log</p><h3>SMART attribute table</h3></div><span>All attributes available in this snapshot · updated ${new Date().toLocaleTimeString()}</span></div><div class="table-card"><table class="smart-full-table"><thead><tr><th>ID</th><th>Attribute</th><th>Current</th><th>Worst</th><th>Threshold</th><th>Raw value</th></tr></thead><tbody>${smartRows}</tbody></table></div></section><section class="workspace-section"><div class="workspace-section-head"><div><p class="eyebrow">Complete device log</p><h3>Seagate FARM table</h3></div><span>Field Accessible Reliability Metrics</span></div><div class="table-card"><table class="farm-table"><thead><tr><th>Metric</th><th>Value</th><th>Source</th><th>Interpretation</th></tr></thead><tbody>${farmRows}</tbody></table></div></section><section class="workspace-section"><div class="workspace-section-head"><div><p class="eyebrow">Evidence timeline</p><h3>All tests for this drive</h3></div><span>${jobs.length} retained job${jobs.length===1?"":"s"}</span></div><div class="table-card"><table><thead><tr><th>Job</th><th>Test</th><th>Status</th><th>Progress</th><th>Phase</th><th>Performance</th></tr></thead><tbody>${historyRows}</tbody></table></div></section>`;
  workspace.scrollTop=savedScroll;if(focusedId)document.getElementById(focusedId)?.focus({preventScroll:true});
}
function openSmart(id){
  const d=data.drives.find(x=>x.id===id);selectedSmart=id;$("#smart-drive-name").textContent=d.model;const active=data.tests.find(t=>t.driveId===id&&["running","paused","queued"].includes(t.status));
  $("#smart-running-note").innerHTML=active?`<strong>Telemetry remains available.</strong> ${active.kind} is ${active.status} at ${active.progress.toFixed(1)}%. SMART is collected through a separate deadline-bound worker.`:`No test is currently active on this drive.`;
  $("#smart-overview").innerHTML=[["Overall health",d.smart],["Temperature",d.temp],["Power-on time",d.hours],["Pending sectors",d.pending]].map(([l,v])=>`<div class="smart-metric"><span>${l}</span><strong>${v}</strong></div>`).join("");
  $("#smart-integrity").className=`integrity-card ${d.integrity}`;$("#smart-integrity").innerHTML=`<h3>${d.integrityLabel}</h3>${d.integrityEvidence.map(item=>`<p>• ${esc(item)}</p>`).join("")}<p><strong>Heuristic only:</strong> this flags inconsistent or reset-looking counters; it does not prove intentional tampering.</p>`;
  $("#smart-table").innerHTML=d.attributes.length?`<table><thead><tr><th>ID</th><th>Attribute</th><th>Current</th><th>Worst</th><th>Threshold</th><th>Raw</th></tr></thead><tbody>${d.attributes.map(a=>`<tr>${a.map((v,i)=>`<td>${i===1?`<strong>${v}</strong>`:v}</td>`).join("")}</tr>`).join("")}</tbody></table>`:`<div class="empty">This transport does not expose SMART attributes.</div>`;
  $("#farm-content").innerHTML=d.farmData.length?`<div class="farm-grid">${d.farmData.map(([l,v])=>`<div class="farm-item"><span>${l}</span><strong>${v}</strong></div>`).join("")}</div>`:`<div class="empty">${d.farm==="Not applicable"?"FARM is a Seagate HDD capability and does not apply to this device.":"FARM is unavailable through this transport."}</div>`;
  $("#smart-updated").textContent=`Updated ${new Date().toLocaleTimeString()}`;$("#smart-dialog").showModal();
}
$$(".nav-item").forEach(b=>b.addEventListener("click",()=>{$$(".nav-item,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(`.page[data-page="${b.dataset.page}"]`).classList.add("active")}));
document.addEventListener("click",e=>{
  const detail=e.target.closest("[data-drive-detail]");if(detail){openDriveWorkspace(detail.dataset.driveDetail);return}
  const discover=e.target.closest("[data-action=discover]");if(discover){discover.disabled=true;toast("Isolated discovery worker started");setTimeout(()=>{discover.disabled=false;toast("Inventory refreshed · SMART remained responsive during active tests")},900);return}
  const run=e.target.closest("[data-test]");if(run){const d=data.drives.find(x=>x.id===run.dataset.test),form=$("#test-form");form.elements.driveId.value=d.id;form.elements.serial.value="";$("#dialog-drive").textContent=d.model;$("#destructive-warning").hidden=true;$("#test-dialog").showModal();return}
  const retry=e.target.closest("[data-retry]");if(retry){toast("Retry refused: the original blocked worker is still present");return}
  const smart=e.target.closest("[data-smart]");if(smart){openSmart(smart.dataset.smart);return}
  const action=e.target.closest("[data-job]");if(action){jobAction(action.dataset.id,action.dataset.job);return}
  const report=e.target.closest("[data-report]");if(report){openReport(data.reports.find(r=>r.id===report.dataset.report));return}
  const verify=e.target.closest("[data-verify]");if(verify){toast(`Checksum verified · ${verify.dataset.verify} is unchanged`);return}
});
document.addEventListener("change",e=>{if(e.target.id==="workspace-test-select"){selectedDetailTest=e.target.value;renderDriveWorkspace()}});
$$('#test-form input[name="profiles"]').forEach(box=>box.addEventListener("change",()=>{$("#destructive-warning").hidden=!$$('#test-form input[name="profiles"]:checked').some(x=>x.value==="destructive_verify")}));
$("#test-form").addEventListener("submit",e=>{
  if(e.submitter?.value==="cancel")return;e.preventDefault();const form=e.currentTarget,d=data.drives.find(x=>x.id===form.elements.driveId.value),selected=$$('#test-form input[name="profiles"]:checked').map(x=>x.value);
  if(!selected.length){toast("Select at least one test");return}if(selected.includes("destructive_verify")&&form.elements.serial.value!==d.serial){toast("Serial confirmation does not match");return}
  const suite=`SUITE-${nextSuite++}`,created=[];selected.forEach((kind,index)=>{const id=`JOB-${nextJob++}`;created.push({id,suite,step:index+1,totalSteps:selected.length,drive:d.path,driveId:d.id,kind:labels[kind],kindId:kind,status:index===0?"running":"queued",progress:0,phase:index===0?"Starting isolated worker":`Waiting for step ${index+1}`,speed:"—",created:"Just now",errors:0,badBlocks:[],slowBlocks:[]})});
  data.tests.unshift(...created);data.audit.unshift({time:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit",second:"2-digit"}),action:"suite.start",actor:"demo-admin",target:`${suite} · ${selected.length} tests`});form.closest("dialog").close();render();toast(`${suite} queued · ${selected.length} tests will run sequentially`);
});
function jobAction(id,action){
  const t=data.tests.find(x=>x.id===id);if(!t)return;
  if(action==="map"){selectedMapJob=id;showPage("tests");render();document.querySelector(".scan-panel").scrollIntoView({behavior:"smooth"});return}
  if(action==="pause"){t.status="paused";t.phase=`Paused at ${t.progress.toFixed(1)}% checkpoint`;toast(`${id} paused safely`)}
  else if(action==="resume"){t.status="running";t.phase="Resumed from durable checkpoint";toast(`${id} resumed`)}
  else if(action==="cancel"){data.tests.filter(x=>x.suite===t.suite&&["running","queued","paused"].includes(x.status)).forEach(x=>{x.status="cancelled";x.phase="Suite cancelled by demo-admin"});toast(`${t.suite} cancelled`)}
  else if(action==="report")createReport(t);render();
}
function advanceSuite(done){
  const next=data.tests.find(t=>t.suite===done.suite&&t.step===done.step+1&&t.status==="queued");if(next){next.status="running";next.phase="Starting next suite step";toast(`${done.suite}: step ${next.step} of ${next.totalSteps} started`)}
}
function showPage(name){$$(".nav-item,.page").forEach(x=>x.classList.remove("active"));$(`.nav-item[data-page="${name}"]`).classList.add("active");$(`.page[data-page="${name}"]`).classList.add("active")}
function createReport(t){const r={id:`RPT-${Math.random().toString(16).slice(2,8).toUpperCase()}`,job:t.id,drive:data.drives.find(d=>d.id===t.driveId)?.model||t.drive,verdict:t.status==="warning"?"WARNING":"PASS",created:"Just now",hash:fakeHash(t.id+Date.now())};data.reports.unshift(r);openReport(r);render()}
function reportContext(r){const job=data.tests.find(t=>t.id===r.job),drive=data.drives.find(d=>d.id===job?.driveId)||data.drives.find(d=>d.model===r.drive),surface=data.tests.find(t=>t.driveId===drive?.id&&t.kindId==="surface_read");return{job,drive,surface}}
function openReport(r){selectedReport=r;const{job,drive,surface}=reportContext(r);$("#report-preview").innerHTML=`<div class="report-sheet"><p>Northstar Drive Lab</p><h3>Drive Diagnostic Report</h3><dl><dt>Report ID</dt><dd>${r.id}</dd><dt>Drive</dt><dd>${drive?.model||r.drive}</dd><dt>Serial</dt><dd>${drive?.serial||"—"}</dd><dt>Source job</dt><dd>${r.job}</dd><dt>Verdict</dt><dd>${r.verdict}</dd><dt>SMART health</dt><dd>${drive?.smart||"Unavailable"}</dd><dt>History analysis</dt><dd>${drive?.integrityLabel||"Indeterminate"}</dd><dt>Surface scan</dt><dd>${surface?`${surface.progress.toFixed(1)}% · ${surface.errors} unreadable`:"Not run"}</dd><dt>Generated</dt><dd>${r.created}</dd><dt>Manifest SHA-256</dt><dd class="hash">${r.hash}</dd></dl><p>The exported PDF includes styled SMART and FARM tables, test details, history-reset evidence, and the color-coded sector map.</p></div>`;$("#report-dialog").showModal()}
$$("[data-close-report]").forEach(b=>b.addEventListener("click",()=>$("#report-dialog").close()));$$("[data-close-smart]").forEach(b=>b.addEventListener("click",()=>$("#smart-dialog").close()));$$("[data-close-workspace]").forEach(b=>b.addEventListener("click",()=>$("#drive-workspace").close()));
$("#drive-workspace").addEventListener("close",()=>{selectedDetailDrive=null;selectedDetailTest=null});
$("#refresh-smart").addEventListener("click",()=>{if(selectedSmart)openSmartRefresh(selectedSmart)});
function openSmartRefresh(id){const d=data.drives.find(x=>x.id===id);if(d.status==="quarantined"){toast("SMART refresh suppressed: drive remains quarantined");return}$("#smart-updated").textContent=`Updated ${new Date().toLocaleTimeString()}`;toast(`SMART refreshed independently for ${d.path}`)}
$("#map-test-select").addEventListener("change",e=>{selectedMapJob=e.target.value;renderDriveMap()});
$("#download-report").addEventListener("click",()=>{if(!selectedReport)return;const pdf=styledReportPDF(selectedReport),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([pdf],{type:"application/pdf"}));a.download=`${selectedReport.id}-detailed.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Styled two-page diagnostic PDF generated locally")});
$("#settings-form").addEventListener("submit",e=>{e.preventDefault();data.audit.unshift({time:new Date().toLocaleTimeString(),action:"settings.update",actor:"demo-admin",target:"system"});render();toast("Demo settings saved")});
$("#user-form").addEventListener("submit",e=>{e.preventDefault();const f=e.currentTarget;data.users.push({name:f.elements.username.value,role:f.elements.role.value});f.reset();render();toast("Demo user added")});
$("#profile-form").addEventListener("submit",e=>{e.preventDefault();toast(`Advanced profile “${e.currentTarget.elements.name.value}” created`);e.currentTarget.reset()});
$("#policy-form").addEventListener("submit",e=>{e.preventDefault();toast("Grading policy saved as a new immutable version")});
$("#reset-demo").addEventListener("click",()=>{data=seed();selectedMapJob="JOB-1048";selectedDetailDrive=null;selectedDetailTest=null;if($("#drive-workspace").open)$("#drive-workspace").close();render();toast("Demo data reset")});
setInterval(()=>{for(const t of data.tests){if(t.status!=="running")continue;t.progress=Math.min(100,t.progress+.28);if(t.kindId==="surface_read"){t.phase=`Reading LBA range · ${t.progress.toFixed(1)}%`;t.speed="238 MB/s";const current=Math.floor(384*t.progress/100);if(current===211&&!t.slowBlocks.includes(211))t.slowBlocks.push(211)}else t.phase=t.progress>=100?"Completed successfully":`Running suite step ${t.step} · ${t.progress.toFixed(1)}%`;if(t.progress>=100){t.status="completed";t.speed=t.kindId==="speed"?"6.74 GB/s · 1.18M IOPS":t.speed;advanceSuite(t)}}render()},900);
setInterval(()=>$("#clock").textContent=`Updated ${new Date().toLocaleTimeString()}`,1000);
function fakeHash(input){let h=2166136261;for(const c of input)h=Math.imul(h^c.charCodeAt(0),16777619);return Array.from({length:8},(_,i)=>(h^(i*0x9e3779b9)>>>0).toString(16).padStart(8,"0")).join("")}
function styledReportPDF(report){
  const{job,drive,surface}=reportContext(report),pages=[[],[]],purple=[.31,.22,.55],ink=[.12,.11,.14],muted=[.37,.35,.4],paper=[.97,.95,.98],green=[.08,.42,.18],red=[.7,.12,.1],amber=[.78,.48,.02],white=[1,1,1];
  const ascii=value=>String(value??"").replace(/[^\x20-\x7E]/g,"?"),pdfEscape=value=>ascii(value).replaceAll("\\","\\\\").replaceAll("(","\\(").replaceAll(")","\\)");
  const color=c=>c.map(v=>Number(v).toFixed(3)).join(" ");
  const rect=(p,x,y,w,h,c)=>pages[p].push(`${color(c)} rg ${x} ${y} ${w} ${h} re f\n`);
  const line=(p,x1,y1,x2,y2,c=[.85,.83,.87])=>pages[p].push(`${color(c)} RG .7 w ${x1} ${y1} m ${x2} ${y2} l S\n`);
  const text=(p,x,y,size,value,bold=false,c=ink)=>pages[p].push(`${color(c)} rg BT /${bold?"F2":"F1"} ${size} Tf ${x} ${y} Td (${pdfEscape(value)}) Tj ET\n`);
  const wrap=(value,maxChars)=>{const words=ascii(value).split(/\s+/),rows=[];let row="";for(const word of words){if((row+" "+word).trim().length>maxChars&&row){rows.push(row);row=word}else row=(row+" "+word).trim()}if(row)rows.push(row);return rows};
  const wrapped=(p,x,y,size,value,maxChars,leading=13,bold=false,c=ink)=>{for(const row of wrap(value,maxChars)){text(p,x,y,size,row,bold,c);y-=leading}return y};
  const labelValue=(p,x,y,label,value)=>{text(p,x,y,7,label.toUpperCase(),true,muted);text(p,x,y-15,11,value,true,ink)};
  const header=(p,pageTitle,pageNumber)=>{rect(p,0,732,612,110,purple);text(p,42,801,11,"DRIVARR / NORTHSTAR DRIVE LAB",true,white);text(p,42,767,25,pageTitle,true,white);text(p,524,801,9,`PAGE ${pageNumber} / 2`,true,white);text(p,42,26,7,`Report ${report.id}  |  SHA-256 ${report.hash.slice(0,24)}...`,false,muted);text(p,534,26,7,"DEMO",true,muted)};
  const integrityColor=drive?.integrity==="suspicious"?red:drive?.integrity==="consistent"?green:amber;

  header(0,"Drive diagnostic report",1);
  text(0,42,705,8,"REPORT ID",true,muted);text(0,42,686,12,report.id,true,ink);
  text(0,220,705,8,"GENERATED",true,muted);text(0,220,686,10,new Date().toLocaleString(),false,ink);
  rect(0,455,675,115,31,integrityColor);text(0,468,687,10,report.verdict,true,white);
  text(0,42,642,15,drive?.model||report.drive,true,ink);text(0,42,624,9,`${drive?.path||"Unknown path"}  /  ${drive?.transport||"Unknown transport"}  /  ${drive?.capacity||"Unknown capacity"}`,false,muted);
  line(0,42,605,570,605);
  labelValue(0,42,582,"Serial number",drive?.serial||"Unavailable");labelValue(0,190,582,"SMART health",drive?.smart||"Unavailable");labelValue(0,338,582,"Temperature",drive?.temp||"Unavailable");labelValue(0,470,582,"Power-on time",drive?.hours||"Unavailable");
  text(0,42,531,12,"SMART history consistency",true,ink);rect(0,42,489,528,31,[.94,.92,.96]);rect(0,42,489,6,31,integrityColor);text(0,61,501,10,drive?.integrityLabel||"Indeterminate",true,integrityColor);
  let evidenceY=472;for(const evidence of drive?.integrityEvidence||["No consistency evidence available."]){evidenceY=wrapped(0,52,evidenceY,8,`- ${evidence}`,92,11,false,muted)}
  text(0,42,430,12,"SMART attributes",true,ink);
  rect(0,42,400,528,22,purple);["ID","Attribute","Current","Worst","Threshold","Raw value"].forEach((h,i)=>text(0,[49,78,290,354,414,478][i],408,7,h.toUpperCase(),true,white));
  let rowY=381;const attrs=(drive?.attributes||[]).slice(0,9);for(let index=0;index<attrs.length;index++){const a=attrs[index];if(index%2===0)rect(0,42,rowY-7,528,22,paper);text(0,49,rowY,8,a[0],false,ink);text(0,78,rowY,8,a[1],true,ink);text(0,302,rowY,8,a[2],false,ink);text(0,365,rowY,8,a[3],false,ink);text(0,430,rowY,8,a[4],false,ink);text(0,478,rowY,8,a[5],false,ink);rowY-=24}
  if(!attrs.length)text(0,52,375,9,"SMART attributes unavailable through this transport.",false,muted);
  text(0,42,132,8,"ASSESSMENT NOTE",true,muted);wrapped(0,42,115,8,"Possible SMART-history reset detection is heuristic. It compares independent lifetime counters, workload totals, power cycles, and FARM data for contradictions; it cannot prove intentional tampering from one snapshot.",100,11,false,muted);

  header(1,"Evidence and surface map",2);
  text(1,42,704,12,"Seagate FARM metrics",true,ink);
  const farm=drive?.farmData||[];if(farm.length){farm.slice(0,6).forEach(([label,value],i)=>{const col=i%3,row=Math.floor(i/3),x=42+col*176,y=640-row*61;rect(1,x,y,164,49,paper);text(1,x+11,y+30,7,label.toUpperCase(),true,muted);text(1,x+11,y+12,11,value,true,ink)})}else text(1,42,675,9,drive?.farm==="Not applicable"?"FARM does not apply to this device.":"FARM data unavailable.",false,muted);
  text(1,42,555,12,"Test suite evidence",true,ink);rect(1,42,525,528,22,purple);["Step","Test","Status","Progress","Result / speed"].forEach((h,i)=>text(1,[49,91,312,390,460][i],533,7,h.toUpperCase(),true,white));
  const suiteTests=job?data.tests.filter(t=>t.suite===job.suite):[];let testY=506;for(const t of suiteTests.slice(0,5)){text(1,54,testY,8,`${t.step}/${t.totalSteps}`,true,ink);text(1,91,testY,8,t.kind,true,ink);text(1,312,testY,8,statusText(t.status),false,ink);text(1,395,testY,8,`${t.progress.toFixed(1)}%`,false,ink);text(1,460,testY,8,t.speed,false,ink);line(1,42,testY-9,570,testY-9);testY-=25}
  if(!suiteTests.length)text(1,52,502,9,"No suite details were retained for this report.",false,muted);
  text(1,42,377,12,"Bad-block surface map",true,ink);text(1,42,360,8,surface?`${surface.drive}  /  ${surface.progress.toFixed(1)}% scanned  /  ${surface.errors} unreadable ranges  /  ${surface.slowBlocks?.length||0} slow or retry ranges`:"No surface scan is associated with this drive.",false,muted);
  const mapCells=192,mapScanned=surface?Math.floor(mapCells*surface.progress/100):0,bad=new Set((surface?.badBlocks||[]).map(x=>Math.floor(x/2))),slow=new Set((surface?.slowBlocks||[]).map(x=>Math.floor(x/2)));
  for(let i=0;i<mapCells;i++){const col=i%24,row=Math.floor(i/24),x=42+col*22,y=326-row*17;let c=[.72,.7,.75];if(surface&&i<=mapScanned)c=bad.has(i)?red:slow.has(i)?amber:i===mapScanned?purple:green;rect(1,x,y,18,12,c)}
  text(1,42,175,7,"GREEN  READ OK",true,green);text(1,146,175,7,"PURPLE  CURRENT",true,purple);text(1,270,175,7,"AMBER  SLOW / RETRY",true,amber);text(1,414,175,7,"RED  UNREADABLE",true,red);
  text(1,42,137,11,"Integrity manifest",true,ink);text(1,42,118,8,report.hash,false,muted);text(1,42,92,8,"Included evidence: normalized SMART, raw values, FARM summary, suite parameters, surface-map state, grading verdict, and operator audit reference.",false,muted);
  text(1,42,62,8,"DEMO REPORT - no physical hardware was tested. Production reports preserve immutable raw evidence and tool versions.",true,red);
  return buildVectorPDF(pages.map(page=>page.join("")));
}
function buildVectorPDF(streams){
  const objects=["<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R 4 0 R] /Count 2 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 7 0 R >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 8 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",...streams.map(stream=>`<< /Length ${stream.length} >>\nstream\n${stream}endstream`)],offsets=[0];let out="%PDF-1.4\n";objects.forEach((object,index)=>{offsets.push(out.length);out+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`+offsets.slice(1).map(offset=>`${String(offset).padStart(10,"0")} 00000 n \n`).join("")+`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return out
}
render();$("#clock").textContent=`Updated ${new Date().toLocaleTimeString()}`;
